export const RANDOM_BACKGROUNDS = [
  "Once won a staring contest with a cat. The cat still sends holiday cards.",
  "Professional cloud shape interpreter with a minor in rainbow chasing.",
  "Can communicate with plants, but they're all terrible gossips.",
  "Accidentally discovered time travel while making a sandwich. Forgot the recipe.",
  "Has a collection of invisible hats. Claims they're just very well hidden.",
  "Trained a group of squirrels to perform Shakespeare. They prefer comedies.",
  "Claims to be allergic to Mondays. Doctor remains skeptical.",
  "Once taught a fish to walk. It wasn't very good at it.",
  "Professional bubble wrap popper with a perfect record.",
  "Can speak backwards fluently, but only while hopping on one foot.",
  "Has a PhD in unicorn psychology from a very prestigious imaginary university.",
  "Former professional pillow fort architect. Retired undefeated.",
  "Once arm-wrestled a ghost. Still argues about who actually won.",
  "Certified dragon whisperer. Currently between dragons.",
  "Invented a new color but forgot to write down the recipe.",
  "Official taste-tester for imaginary restaurants. Five-star reviews only.",
  "Holds the world record for most socks lost in the dryer dimension.",
  "Part-time cloud sculptor. Specializes in fluffy bunnies and dragons.",
  "Professional butterfly whisperer who only works on Tuesdays.",
  "Retired superhero whose power was making plants grow slightly faster.",
  "Collects the echoes of laughter in tiny glass jars for rainy days.",
  "Moonlights as a dream architect but keeps falling asleep on the job.",
  "Expert in translating cat meows. Mostly complaints about dinner time.",
  "Certified unicorn groomer with a specialty in rainbow mane maintenance.",
  "Time traveler who only visits breakfast times throughout history.",
  "Professional raindrop racer. Holds several window-track records.",
  "Teaches meditation to stressed-out garden gnomes on weekends.",
  "Runs an underground library for banned knock-knock jokes.",
  "Apprentice wizard who accidentally turned themselves polka-dotted.",
  "Cosmic joke teller whose punchlines arrive three days later.",
  "Retired mermaid who now teaches synchronized swimming to penguins.",
  "Collector of forgotten dreams and slightly used wishes.",
  "Professional cloud taster. Claims they're getting less fluffy each year.",
  "Accidental inventor of invisible socks. Still can't find them.",
  "Guardian of the world's smallest infinity. Keeps it in a teacup.",
  "Trains dust bunnies for stealth operations under furniture.",
  "Certified leprechaun negotiator. Payment accepted in lucky charms.",
  "Expert in the ancient art of origami shadow puppets.",
  "Retired sandcastle architect. Specializes in underwater developments.",
  "Professional starlight collector on cloudy nights.",
  "Freelance dream architect specializing in flying pizza scenarios.",
  "Retired rainbow taste tester with a golden tongue certification.",
  "Professional parallel universe tour guide, never lost a tourist.",
  "Master of the ancient art of tickling thunderclouds.",
  "Certified unicorn flight instructor with perfect safety record.",
  "Expert in teaching old dogs new, increasingly improbable tricks.",
  "Renowned collector of bottled sunsets and morning dew.",
  "Professional wishing star quality control inspector.",
  "Accidental inventor of edible poetry, tastes like purple.",
  "Guardian of the world's most elusive knock-knock joke.",
  "Retired professional deja vu coordinator.",
  "Holds the record for most simultaneous daydreams.",
  "Licensed fairy godparent with a specialty in pumpkin vehicles.",
  "Teaches interpretive dance to shy mountains.",
  "Certified imagination safety inspector and dream debugger.",
  "Professional moonbeam weaver and starlight tailor.",
  "Expert in translating whale songs into interpretive dance.",
  "Retired professional cloud sculptor with a fear of heights.",
  "Master practitioner of reverse psychology on stubborn shadows.",
  "Teaches philosophy to houseplants. The cacti are particularly cynical.",
  "Runs a dating service for left socks looking for their right partners.",
  "Certified rainbow inspector. Always finds the pot of gold, never tells.",
  "Professional bubble artist who only works in zero gravity.",
  "Keeper of forgotten melodies and misplaced dance moves.",
  "Expert in convincing shadows to behave themselves.",
  "Retired tooth fairy consultant. Specialized in premium tooth valuations.",
  "Trains butterflies for synchronized flying competitions.",
  "Professional cloud herder. Keeps them from raining on parades.",
  "Master of invisible ink calligraphy. No one has seen their work."
];

export function getRandomBackground(): string {
  return RANDOM_BACKGROUNDS[Math.floor(Math.random() * RANDOM_BACKGROUNDS.length)];
}